### ISSUE TITLE
Legacy tags creating confusion for CocoaPods

### ISSUE THREAD

**Issue by tzm41** [segment-integrations/analytics-ios-integration-flurry#10]
Some older releases have version number higher than newer releases, creating confusion for CocoaPods, who thinks there is an update to the pod. It would be cool if those could be cleaned up.
<img width="602" alt="screen shot 2017-06-23 at 11 25 10 am" src="https://user-images.githubusercontent.com/5728283/27488897-ada1b20c-5806-11e7-865b-de6080d8893d.png">

**Comment by tzm41** [comment]
Cross posting a comment in https://github.com/CocoaPods/cocoapods.org/issues/339, currently Segment-Flurry `7.3.1-alpha` is gone, but still seeing Segment-Flurry `7.3.0-alpha`, both in the web search, and in the result of `pod outdated`.

**Comment by ladanazita** [comment]
Hey @tzm41 , I haven't looked into this yet but that sounds like we need to go through and delete every legacy tag that is > current. Let me investigate.

**Comment by tzm41** [comment]
Thank you!
