### ISSUE TITLE
Bump target down to iOS 7.0 in Podspec

### ISSUE THREAD

**Issue by jacobmoncur** [segment-integrations/analytics-ios-integration-flurry#4]
Doesn't seem like there is a good reason why the minimum target is `8.0` and not `7.0`. Since https://github.com/segmentio/analytics-ios minimum target is `7.0` would be good to bring min target down to `7.0` for this library as well.

**Comment by f2prateek** [comment]
Yup seems reasonable - wanna send us a PR :)?

**Comment by jacobmoncur** [comment]
Done and done ---> #5
