### ISSUE TITLE
Carthage ?

### ISSUE THREAD

**Issue by smhk** [segment-integrations/analytics-ios-integration-flurry#7]
Dudes where the heck is Carthage support for this one (and the google one) ???

thx

**Comment by f2prateek** [comment]
The bundled integrations don't support Carthage at the moment. It's not a highly requested feature, so it's not on our immediate roadmap at the moment. However, we're happy to review and accept PRs adding Carthage support.

**Comment by f2prateek** [comment]
Note: I don't think the Flurry (https://github.com/flurry/flurry-ios-sdk) SDK supports Carthage https://github.com/flurry/flurry-ios-sdk/issues/16#issuecomment-166354957. If that's still the case, then of course, neither will the integration.

**Comment by f2prateek** [comment]
I'm also not sure if Google Analytics supports Carthage.

On a general note, in the meantime, for other tools that do support Carthage, you can also probably do something like this in your Cartfile

```
// The core iOS library.
github "segmentio/analytics-ios" 

// The tool's native SDK.
// Note flurry is just being used as an example here - but it doesn't support Carthage.
github "flurry/flurry-ios-sdk"
```

And then copy the integration files (e.g. for Flurry copy https://github.com/segment-integrations/analytics-ios-integration-flurry/tree/master/Pod/Classes), either manually or using gitsubmodules.

**Comment by smhk** [comment]
Hey Prateek, thanks for the quick response.

In short it looks like it's really best to stick with cocoapods?

We are adding Segment with flurry/goog in our case.

As long as I've got you here, there's some confusion whether the pod should look like this ..

```
dependencies {
pod 'Analytics', '~> 3.0 '
pod "Segment-Flurry"
pod "Segment-Googlenalytics"
}
```

or like this ..

```
pod 'Analytics', '~> 3.0 '
pod "Segment-Flurry"
pod "Segment-Googlenalytics"
```

Cheers, thanks again.

Thought - almost everyone who does use Segment, integrates one of Flurry etc.  For this reason, it's actually a bit of a time waste mentioning that the Segment library (as such) has carthage support - since in practice you can't really use it.  Cheers

**Comment by f2prateek** [comment]
There are certainly pros and cons of using CocoaPods over Carthage. But with Segment, CocoaPods is the preferred installation method. And if you want to use Flurry, I don't think you have the option of using Carthage anyways since their SDK doesn't support Carthage from what I can tell, and they also don't have a server side API so we can't route the data to them via our servers.

Regarding the syntax, the Podfile should looks like the 2nd option you posted:

```
pod 'Analytics', '~> 3.0 '
pod "Segment-Flurry"
pod "Segment-GoogleAnalytics"
```

**Comment by smhk** [comment]
Thanks again for the particularly prompt response - have a good day now!  Cheers

**Comment by smhk** [comment]
It's certainly a bit of a challenge to use the cocoapods version in a SWIFT PROJECT.

I've turned on frameworks

```
$ cat Podfile
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
target 'AppName' do
pod 'Analytics', '~> 3.0 '
pod "Segment-Flurry"
pod "Segment-GoogleAnalytics"
end
```

and pod installed;

the project then seems to just not find
import Analytics

Tricky one : O

**Comment by f2prateek** [comment]
If you write in to friends@segment.com, our team can help. To aid debugging, you might want to try with just the Analytics pod first, and then work on the integration ones.

**Comment by smhk** [comment]
Thanks, I'll do that.

I seemed to get it working. I posted a question here

https://community.segment.com/t/636n4h/flurry-integration-not-receiving-ios-data

for one of your colleagues also; the code samples in there may help anyone googling here. Cheers.
